In [2]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset=pd.read_csv('dataset/smallDataSet.csv')

In [4]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [5]:
X

array([['SF', 146, 0, ..., 0, 0, 0],
       ['S0', 0, 0, ..., 0, 0, 0],
       ['SF', 232, 8153, ..., 0, 1, 0],
       ..., 
       ['SF', 2628, 3860, ..., 0, 1, 1],
       ['SF', 4, 0, ..., 0, 0, 0],
       ['SF', 0, 2072, ..., 0, 1, 0]], dtype=object)

In [7]:
y

array([0, 0, 0, ..., 1, 0, 1], dtype=int64)

Use Label to the rows with numerical value

In [11]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
labelencoder_X_3 = LabelEncoder()
X[:, 0] = labelencoder_X_3.fit_transform(X[:, 3])

In [12]:
X

array([[0, 39, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 88, 310, ..., 0, 1, 0],
       ..., 
       [0, 270, 267, ..., 0, 1, 1],
       [0, 2, 0, ..., 0, 0, 0],
       [0, 0, 218, ..., 0, 1, 0]], dtype=object)

In [13]:
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

In [14]:
X

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  1.,  1.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.]])

In [15]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [16]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [19]:
X_test

array([[-0.1       , -0.03520167, -0.18234057, ..., -0.03520167,
        -0.80977633, -0.10950053],
       [-0.1       , -0.03520167, -0.18234057, ..., -0.03520167,
         1.2349089 , -0.10950053],
       [-0.1       , -0.03520167, -0.18234057, ..., -0.03520167,
        -0.80977633, -0.10950053],
       ..., 
       [-0.1       , -0.03520167, -0.18234057, ..., -0.03520167,
         1.2349089 , -0.10950053],
       [-0.1       , -0.03520167, -0.18234057, ..., -0.03520167,
        -0.80977633, -0.10950053],
       [-0.1       , -0.03520167, -0.18234057, ..., -0.03520167,
        -0.80977633, -0.10950053]])

In [20]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

ModuleNotFoundError: No module named 'keras'